# Generated by blueprint from Blueprint.roc. Do not edit.
{
  description = "Development environments for full";

  inputs = {
    "default".url = "github:NixOS/nixpkgs/nixos-unstable";
    "stable".url = "github:NixOS/nixpkgs/nixos-24.05";
    "roc".url = "github:roc-lang/roc-overlay";
    "utils".url = "github:numtide/flake-utils";
  };

  outputs = { self, ... }@inputs:
    let
      environmentsFor = system: {
        "dev" = let
          overlays = [ inputs."roc".overlays.default ];
          sets = {
            "default" = import inputs."default" { inherit system overlays; };
            "stable" = import inputs."stable" { inherit system overlays; };
          };
        in extra: sets."default".mkShell ({
          packages = [
            sets."default"."hello"
            sets."stable"."jq"
          ];
        } // extra);
        "empty" = let
          overlays = [  ];
          sets = {
            "default" = import inputs."default" { inherit system overlays; };
          };
        in extra: sets."default".mkShell ({
          packages = [
          ];
        } // extra);
        "headless" = let
          overlays = [  ];
          sets = {
            "stable" = import inputs."stable" { inherit system overlays; };
          };
        in extra: sets."stable".mkShell ({
          packages = [
            sets."stable"."jq"
          ];
        } // extra);
      };
    in
    {
      devShells = {
        "x86_64-linux" = let
          environments = environmentsFor "x86_64-linux";
        in {
          "blueprint-env-dev" = environments."dev" { };
          "blueprint-env-empty" = environments."empty" { };
          "blueprint-env-headless" = environments."headless" { };
          "default" = environments."dev" { "shellHook" = "echo \"hi \${USER}\"\nexport FOO=bar\n"; "GREETING" = "hello"; };
          "empty" = environments."empty" { };
        };
        "aarch64-linux" = let
          environments = environmentsFor "aarch64-linux";
        in {
          "blueprint-env-dev" = environments."dev" { };
          "blueprint-env-empty" = environments."empty" { };
          "blueprint-env-headless" = environments."headless" { };
          "default" = environments."dev" { "shellHook" = "echo \"hi \${USER}\"\nexport FOO=bar\n"; "GREETING" = "hello"; };
          "empty" = environments."empty" { };
        };
        "x86_64-darwin" = let
          environments = environmentsFor "x86_64-darwin";
        in {
          "blueprint-env-dev" = environments."dev" { };
          "blueprint-env-empty" = environments."empty" { };
          "blueprint-env-headless" = environments."headless" { };
          "default" = environments."dev" { "shellHook" = "echo \"hi \${USER}\"\nexport FOO=bar\n"; "GREETING" = "hello"; };
          "empty" = environments."empty" { };
        };
        "aarch64-darwin" = let
          environments = environmentsFor "aarch64-darwin";
        in {
          "blueprint-env-dev" = environments."dev" { };
          "blueprint-env-empty" = environments."empty" { };
          "blueprint-env-headless" = environments."headless" { };
          "default" = environments."dev" { "shellHook" = "echo \"hi \${USER}\"\nexport FOO=bar\n"; "GREETING" = "hello"; };
          "empty" = environments."empty" { };
        };
      };
      "blueprint" = { "version" = 1; };
    };
}
