((format ((major 2) (minor 0)))
 (name "full")
 (requires ("raw"))
 (systems ("x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin"))
 (sources (((name "stable")
            (provider (NixPackages "github:NixOS/nixpkgs/nixos-24.05")))))
 (inputs (((name "roc") (url "github:roc-lang/roc-overlay") (kind Overlay))
          ((name "utils") (url "github:numtide/flake-utils") (kind Flake))))
 (environments (
   ((name "dev") (parents ())
    (tools (((source "default") (name "hello"))
            ((source "stable") (name "jq")))) (overlays ("roc")))
   ((name "empty") (parents ()) (tools ()) (overlays ()))
   ((name "headless") (parents ())
    (tools (((source "stable") (name "jq")))) (overlays ()))))
 (shells (((name "default") (environment "dev"))
          ((name "empty") (environment "empty"))))
 (tasks (((name "greet") (environment "headless") (run ("jq" "--version")))))
 (raw (((backend "nix") (target "shell:default")
        (value (Attrs (((name "shellHook") (value (Str "echo \"hi ${USER}\"\nexport FOO=bar\n")))
                       ((name "GREETING") (value (Str "hello")))))))
       ((backend "nix") (target "flake")
        (value (Attrs (((name "blueprint") (value (Attrs (((name "version") (value (Int 1)))))))))))
       ((backend "guix") (target "whatever") (value (Int 0))))))
