((format ((major 2) (minor 0)))
 (name "sample \"quoted\"")
 (systems ("x86_64-linux" "aarch64-darwin"))
 (sources (((name "nixpkgs")
            (provider (NixPackages "github:NixOS/nixpkgs/nixos-unstable")))))
 (inputs (((name "roc") (url "github:roc-lang/roc-overlay") (kind Overlay))))
 (environments (
   ((name "base") (parents ())
    (tools (((source "nixpkgs") (name "git")))) (overlays ()))
   ((name "dev") (parents ("base"))
    (tools (((source "nixpkgs") (name "llvmPackages.bintools"))))
    (overlays ("roc")))))
 (shells (((name "default") (environment "dev"))
          ((name "ci") (environment "base")))))
