# Generated by blueprint from Blueprint.roc. Do not edit.
{
  description = "Development environments for sample \"quoted\"";

  inputs = {
    "nixpkgs".url = "github:NixOS/nixpkgs/nixos-unstable";
    "roc".url = "github:roc-lang/roc-overlay";
  };

  outputs = { self, ... }@inputs:
    let
      environmentsFor = system: {
        "base" = let
          overlays = [  ];
          sets = {
            "nixpkgs" = import inputs."nixpkgs" { inherit system overlays; };
          };
        in extra: sets."nixpkgs".mkShell ({
          packages = [
            sets."nixpkgs"."git"
          ];
        } // extra);
        "dev" = let
          overlays = [ inputs."roc".overlays.default ];
          sets = {
            "nixpkgs" = import inputs."nixpkgs" { inherit system overlays; };
          };
        in extra: sets."nixpkgs".mkShell ({
          packages = [
            sets."nixpkgs"."git"
            sets."nixpkgs"."llvmPackages"."bintools"
          ];
        } // extra);
      };
    in
    {
      devShells = {
        "x86_64-linux" = let
          environments = environmentsFor "x86_64-linux";
        in {
          "blueprint-env-base" = environments."base" { };
          "blueprint-env-dev" = environments."dev" { };
          "default" = environments."dev" { };
          "ci" = environments."base" { };
        };
        "aarch64-darwin" = let
          environments = environmentsFor "aarch64-darwin";
        in {
          "blueprint-env-base" = environments."base" { };
          "blueprint-env-dev" = environments."dev" { };
          "default" = environments."dev" { };
          "ci" = environments."base" { };
        };
      };
    };
}
