## Top-level CLI interface and entry point for Kai.
##
## It takes in args from the CLI, validates them, then
## runs the associated commands.
##
## All app I/O and side-effects performed here
## to separate boundaries and keep other code pure and testable.

# If possible, the CLI must contain all side effects to scope them
# the cli must also be generated by the
#
# the cli should have a run fn which takes all the modules and
#
# xkai -> a "kai compiler" that writes cli.roc (kai cli)
#
# xkai is then responsible for:
# - validating that the Command/Backend/Impl structure is present
#   (eventually we should probably scope these to the "determinate system"
#   inputs/outputs so that not just any arbitrary code can run)
#   for at least one command, and that all provided commands conform to it.
# - writing a roc output file which imports all the modules

# xkai will build the binary, great. But then how will that binary run?
# what would this built executable look like?
#
# we probably need some api that handles the "everything else" which is:
# or is all that handled in the library? well, if the module commands are
# going to also define:
# - what gets written to disk
# - what nix commands are run
#
# then maybe they need to define them? can they not just define some contract?
#
# But we also want their to be a standard api of things they write, and handlers
# but the handlers, depending on the expected api's, are effectful, no?

# goal: move the cli.roc, Kai.roc, and Cli.roc as they are to be the "standard lib"
# get them to compile, then test that they have parity. Then refactor stdlib from there

app [main!] {
	pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.21.0-rc4/FvCh4vdqm3nBY6DWEfZ8RuGCVfjuMY43HA8KSNk9qVDn.tar.zst",
}

import pf.OsStr
import pf.Stdout
import pf.Path
import pf.Cmd

import Cli

Plugin := [].{
	# TODO: this will be managed eventually in
	# either kai.roc or in .kai, but for now we
	# localize everything that isn't generic to
	# minimize refactoring later.
	refactor = {
		backend: {
			name: "nix",
			managed_filename: "flake.nix",
			shell_command: "develop",
			shell_command_args: ["path:.kai#default"],
		},
		config_filename: "kai.roc",
		managed_kai_dir: ".kai",
	}

	print_usage! : {} => Try({}, _)
	print_usage! = |_| {
		Stdout.line!(Cli.usage)?
		Ok({})
	}

	run! : List(OsStr) => Try({}, _)
	run! = |args| {
		display_args = args.drop_first(1).map(OsStr.display)
		match Cli.parse(display_args) {
			Cli.Command.Help => print_usage!({})
			Cli.Command.Shell => {
				# We run the kai.roc file via the Roc compiler directly.
				# The platform validates and parses the config,
				# lowering it into the appropriate backend.
				#
				# Around here is where we will eventually include
				# more effectful logic responsible for doing things
				# like
				output = Cmd.new("roc")
					.args([
						refactor.config_filename,
					])
					.exec_output!()?
				# The string output is the resulting backend
				# dev shell config text. For Nix, this is
				# the contents of the flake.nix file.
				source = output.stdout_utf8
				# Kai creates and manages config in .kai under the hood.
				# Things like flake.nix/.lock, the selected backend, etc.
				# are written here.
				managed_kai_dir = Path.utf8(refactor.managed_kai_dir)
				if !Path.exists!(managed_kai_dir)? {
					Path.create_dir!(managed_kai_dir)?
				}
				managed_file = Path.join(
					managed_kai_dir,
					refactor.backend.managed_filename,
				)
				Path.write_utf8!(managed_file, source)?
				Stdout.line!(
					"wrote: ${refactor.backend.managed_filename}",
				)?
				Cmd.exec!(
					refactor.backend.name,
					[
						refactor.backend.shell_command,
					].concat(refactor.backend.shell_command_args),
				)

			}

			Cli.Command.Version => Stdout.line!("kai version ${Cli.version}")
			Cli.Command.Unknown(unknown) => {
				Stdout.line!("Unknown command ${unknown}")?
				print_usage!({})
			}
		}
	}
}
