# Generated by roc-blueprint and roc-blueprint-nix. Do not edit.
{
  "description" = "Development environments for multi-platform-shell";
  "inputs" = {
    "nixpkgs" = {
      "url" = "github:NixOS/nixpkgs/nixos-unstable";
    };
  };
  "outputs" = { nixpkgs, ... }:
    {
      "devShells" = {
        "x86_64-linux" = {
          "default" = nixpkgs."legacyPackages"."x86_64-linux"."mkShell" {
            "packages" = [
              nixpkgs."legacyPackages"."x86_64-linux"."git"
            ];
          };
        };
        "aarch64-darwin" = {
          "default" = nixpkgs."legacyPackages"."aarch64-darwin"."mkShell" {
            "packages" = [
              nixpkgs."legacyPackages"."aarch64-darwin"."git"
            ];
          };
        };
      };
    };
}
